name: "Build and Push Docker Image"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password |
          docker login --username AWS --password-stdin 015389193943.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Build Docker
        run: |
          docker build -t my-backend .

      - name: Tag
        run: |
          docker tag iqbalr/frontend-repository 015389193943.dkr.ecr.ap-southeast-1.amazonaws.com/iqbalr/frontend-repository

      - name: Push
        run: |
          docker push 015389193943.dkr.ecr.ap-southeast-1.amazonaws.com/iqbalr/frontend-repository
